### ISSUE TITLE
Celery error after starting the exporter

### ISSUE THREAD

**Issue by Poil** [OvalMoney/celery-exporter#14]
Hi,

After I start the exporter, this message appear in loop in my Celery logs :

```
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: [2019-10-10 12:42:56,731: ERROR/MainProcess] Control command error: OperationalError("\nCannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.\nProbably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.\n",)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: Traceback (most recent call last):
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    yield
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/connection.py", line 518, in _ensured
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    return fun(*args, **kwargs)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/messaging.py", line 203, in _publish
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    mandatory=mandatory, immediate=immediate,
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 605, in basic_publish
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    message, exchange, routing_key, **kwargs
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/virtual/exchange.py", line 70, in deliver
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    for queue in _lookup(exchange, routing_key):
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/redis.py", line 877, in _lookup
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    exchange, redis_key))
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: kombu.exceptions.InconsistencyError: 
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: 
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: 
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: During handling of the above exception, another exception occurred:
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: 
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: Traceback (most recent call last):
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/celery/worker/pidbox.py", line 46, in on_message
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    self.node.handle_message(body, message)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/pidbox.py", line 145, in handle_message
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    return self.dispatch(**body)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/pidbox.py", line 115, in dispatch
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    ticket=ticket)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/pidbox.py", line 151, in reply
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    serializer=self.mailbox.serializer)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/pidbox.py", line 285, in _publish_reply
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    **opts
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    exchange_name, declare,
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/connection.py", line 551, in _ensured
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    errback and errback(exc, 0)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    self.gen.throw(type, value, traceback)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/connection.py", line 444, in _reraise_as_library_errors
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    sys.exc_info()[2])
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    raise value.with_traceback(tb)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    yield
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/connection.py", line 518, in _ensured
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    return fun(*args, **kwargs)
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/messaging.py", line 203, in _publish
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    mandatory=mandatory, immediate=immediate,
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 605, in basic_publish
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    message, exchange, routing_key, **kwargs
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/virtual/exchange.py", line 70, in deliver
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    for queue in _lookup(exchange, routing_key):
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/redis.py", line 877, in _lookup
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8:    exchange, redis_key))
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: kombu.exceptions.OperationalError: 
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
Oct 10 12:42:56 [localhost] dockerc/pp-bo-celery/1d1823e96df8: Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.
```

Not sure/understanding why, is it a key created by the exporter and removed or other things ?

Best regards,

**Comment by Poil** [comment]
Sorry, it looks like a bug in Celery https://github.com/celery/kombu/issues/1063
