### ISSUE TITLE
Executable binary for isolated hosts

### ISSUE THREAD

**Issue by aned** [OvalMoney/celery-exporter#36]
Is there a way to make an executable binary for isolated hosts? 
The problem is that I need to run it on hosts that don't have internet connection, so I can't install a bunch of dependencies and such. 
I've tried to build it via pip on the same architecture machine that had internet access, moved the binary across but it doesn't work. 

```
$ ./celery-exporter
Traceback (most recent call last):
  File "/blah/./celery-exporter", line 33, in <module>
    sys.exit(load_entry_point('celery-exporter', 'console_scripts', 'celery-exporter')())
  File "/blah/./celery-exporter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: celery-exporter

**Comment by SharpEdgeMarshall** [comment]
You can refer to Dockerfile to see how we compile and move the wheels to the final target.
